docs:
  - template:
      displayName: "generic-connector-0.0.1"
      description: "Generic API Connector documentation"
      sources:
        - type: markdown
          name: docs
          mode: package
          filter: (docs/(.*?)\.(md|svg)$)
