apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "service-broker-proxy.fullname" . }}
  labels:
    app: {{ template "service-broker-proxy.name" . }}
    chart: {{ template "service-broker-proxy.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation
